app-sre/gabi

pkg/cmd/cmd.go
pkg/env/db/db.go

This MR fixes the usage of `pgx` in gabi. The driver is imported from pgx/v4/stdlib to support usage with sql.DB interface. In addition, the constructed connection string now changes format depending on the database type specified in runtime environment variables.

Add Postgres Support

---

pkg/handlers/query.go

This PR adds support for running select queries against the target rds and returns a 2-D string array as result.
The first item of the result will be a list of column names get from rows.Columns(). As the following will be the data result.

support select query

---

go.sum
pkg/audit/audit.go
pkg/cmd/cmd.go
pkg/gabi.go
pkg/handlers/query.go

This PR adds flexible audit support to gabi. Users wishing to add a different audit backend will need to add a struct which implements the Audit.Write() interface. Currently, only stdout logging is supported, with plans in the future to add CloudWatch audit support.
The audit interface is included in gabi's Env struct, which also houses the DB connection pool and logger for passing to handlers.
`2021-07-12T17:15:59.984-0700	INFO	audit/audit.go:22	gabi API audit record	{"Query": "SELECT * FROM company;", "User": "placeholder", "Timestamp": 1626135359}`

Add Audit Support

---

openshift/gabi.template.yaml
pkg/handlers/query.go

This pr add the openshift template for deployment with a openshift OAuth proxy as a sidecar for auth.
User name will be passed by OAuth proxy in the header to upstream.

add openshift template & get audit user from oauth proxy

---

pkg/handlers/healthcheck.go

https://issues.redhat.com/browse/APPSRE-4546
This PR updates the behavior of Gabi's healthcheck to only print a secret-containing SQL connection string in its logs and not in the HTTP response.
Those with access to gabi logs will still be able to see these secrets.

[APPSRE-4546] Address healthcheck secret leak

---

pkg/env/db/db.go

ISSUE:
When utilizing the pgx driver, special characters within DB_PASS caused the connection to fail. 
SOLUTION:
URL encode DB_PASS prior to creating the connection string. 
Note: this is not included in mysql because the mysql driver handles encoding differently and will fail connection if encoded.
Ticket: https://issues.redhat.com/browse/APPSRE-4548

URL encode DB_PASS for pgx driver connection

---

openshift/gabi-no-cluster-resources.template.yaml
openshift/gabi.template.yaml

Customer is trying to execute a long running query with `http --timeout 600`. I assume we wont have much traffic here, so allowing this might be ok?

increase t/o for queries

---

openshift/gabi-no-cluster-resources.template.yaml
openshift/gabi.template.yaml

Right now, we cannot deploy multiple gabi instances to the same namespace. If we parameterize the resource name for gabi, we can achieve this goal.
Signed-off-by: Suzana Nesic <snesic@redhat.com>

adding parameter to resource name to allow for multiple instances

---

openshift/gabi.template.yaml

The template being used up to now was gabi-no-cluster-resources.template.yaml
I copied the content over into this gabi.template.yaml so we get the most recent changes and made the SPLUNK TOKEN and ENDPOINT env var directly as required template params.
Those will be set in app-interface using `secretParameters`
app-interface MR to merge after this one: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/46195
A follow up MR could delete gabi-no-cluster-resources.template.yaml for cleanup.

Embed the splunk creds data in the variable instead of relying on an external secret

---

dashboards/grafana-dashboard-gabi-performance-overview.configmap.yaml

Gabi currently does not have any visualization observability tools associated with the service. This PR is to create that dashboard in order to get the service in a fully onboarded state.
Signed-off-by: Suzana Nesic <snesic@redhat.com>

creating a grafana dashboard for gabi

---

pkg/audit/audit.go

Since Go **1.16**, the **io/ioutil** package has been deprecated (see: [Go 1.16 Release Notes](https://golang.google.cn/doc/go1.16)). Even though the old package, which currently is more of a proxy package, is still available for backward compatibility, it's _preferable_ to use the affected functions directly from the new packages.
Thus, update current users of the **io/ioutil** package so that each uses its respective new package, either **os** or **io**, and then remove **io/ioutil** altogether.
No change to functionality intended.

Remove deprecated io/ioutil package

---

openshift/gabi.template.yaml
pkg/cmd/cmd.go
pkg/handlers/healthcheck.go
test/integration_test.go

Currently, a single middleware-based handler produces HTTP request access logs. This also covers the health check endpoint, which is contacted every few seconds by the Kubernetes liveness probe, leading to an excessive amount of not-so-useful log entries to be generated - most of which consist of simply "200 OK" responses.
Thus, this change reduces the health check endpoint request log generation only to a non-production environment.
While at it, change the health check handler to use the available Zap logger for consistency with the rest of the code base.
Related: [APPSRE-6524](https://issues.redhat.com/browse/APPSRE-6524)

APPSRE-6524: Reduce log creation for the health check endpoint requests

---

pkg/audit/splunk.go
pkg/audit/splunk_test.go
pkg/cmd/cmd.go
pkg/env/db/db.go
pkg/env/db/db_test.go
pkg/env/env.go
pkg/env/splunk/splunk.go
pkg/env/splunk/splunk_test.go
pkg/env/user/user.go
pkg/env/user/user_test.go
pkg/gabi.go
pkg/handlers/healthcheck.go
pkg/handlers/healthcheck_test.go
pkg/handlers/query.go
pkg/handlers/query_test.go
pkg/middleware/audit.go
pkg/middleware/audit_test.go
pkg/middleware/authorization.go
pkg/middleware/authorization_test.go
pkg/middleware/expiration.go
pkg/middleware/expiration_test.go
pkg/middleware/middleware.go
pkg/middleware/recovery.go
pkg/middleware/recovery_test.go
test/helper_test.go
test/integration_test.go

Currently, there isn't a convenient way to pass complex data, either in the request (SQL statements) or in the response (columns and rows; more so rows), especially when either the query or results include one or more characters that the JSON standard otherwise considers reserved.
This often hinders the end-user ability to use the service, especially if the data in the database is stored in a format that would infringe on the limitations JSON use can pose - this might include rich plaintext data or even JSON document (such will require elaborate escaping and quoting) that has been stored in the database, or when the JSONB is used for a column where the results are then finally rendered as JSON document.
Thus, this change adds Base64 support for decoding a query (SQL statement) from the …

APPSRE-7066: Support Base64-encoded value as SQL query and when encoding results

---

go.mod
go.sum

Update GABI to address a recent security vulnerability:
> A maliciously crafted HTTP/2 stream could cause excessive CPU consumption in the HPACK decoder, sufficient to cause a denial of service from a small number of small requests.
The affected package is **golang.org/x/net** (version 6.0 or older).
See https://pkg.go.dev/vuln/GO-2023-1571 for more details.
Related: [APPSRE-7127](https://issues.redhat.com/browse/APPSRE-7127)

Address security vulnerability in the golang.org/x/net package

---

openshift/gabi.template.yaml

Allow values of the CPU and memory requests and limits to be set as parameters rather than to hardcode these.
Thus, these values can be overridden on-demand for different deployments, as needed.

Allow setting CPU and memory requests and limits via parameters

---

openshift/gabi.template.yaml

Keep the names of the parameters as singular for consistency with other projects.

Rename CPU and memory requests and limits parameters for consistency

---

build_deploy.sh
integration.sh
pr_check.sh

Update Go to version ~1.20~1.19, especially to be able to build against Go ~1.20.6~1.19.11, which fixes the following vulnerability:
- [CVE-2023-29406](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2023-29406)
> The HTTP/1 client does not fully validate the contents of the Host header. A maliciously crafted Host header can inject additional headers or entire requests. With fix, the HTTP/1 client now refuses to send requests containing an invalid Request.Host or Request.URL.Host value.
No functional changes are intended.

Update Go to version 1.19

---

openshift/gabi.template.yaml

The upstream container image (see [openshift/origin-oauth-proxy](https://quay.io/repository/openshift/origin-oauth-proxy) on Quay) for the [openshift/oauth-proxy](https://github.com/openshift/oauth-proxy) service, that is Red Hat's fork of the OAuth2 Proxy, finally includes the changes needed to set the desired upstream timeout value.
Thus, enable this command-line argument when deploying a GABI instance now that the functionality is available.
Related:
- [APPSRE-7875](https://issues.redhat.com/browse/APPSRE-7875)
- https://github.com/app-sre/gabi/pull/57

APPSRE-7875: Enable the --upstream-timeout argument

---

openshift/gabi.template.yaml

Set the timeout value for the OpenShift Router to 10 minutes, which is also the new default, to ensure that requests that take a little bit longer are not timed out and, as such, are interrupted abruptly.
While at it, rename the old variable from `SERVER_TIMEOUT` to `OPENSHIFT_ROUTER_TIMEOUT` to remove ambiguity about what is value this variable would otherwise set.
Related:
- [APPSRE-7875](https://issues.redhat.com/browse/APPSRE-7875)
- https://github.com/app-sre/gabi/pull/57
- https://github.com/app-sre/gabi/pull/60
Signed-off-by: Krzysztof Wilczyński [kwilczynski@redhat.com](mailto:kwilczynski@redhat.com)

Set OpenShift Router timeout to a higher default value

---

openshift/gabi.template.yaml

Update the default timeout value from 30 seconds to 5 minutes.
Related:
- [APPSRE-7875](https://issues.redhat.com/browse/APPSRE-7875)
- https://github.com/app-sre/gabi/pull/57
- https://github.com/app-sre/gabi/pull/60
- https://github.com/app-sre/gabi/pull/62
Signed-off-by: Krzysztof Wilczyński [kwilczynski@redhat.com](mailto:kwilczynski@redhat.com)

Update OAuth2 Proxy default timeout value

---

openshift/gabi.template.yaml

Also bump up the base value from 10m to 100m due to errors deploying to stage

Templatize the cpu request for the oauth proxy

---

openshift/gabi.template.yaml
openshift/post-deploy-tests.template.yaml

Use `RESOURCES` to replace `CPU_REQUEST`, `MEMORY_REQUEST`, `MEMORY_LIMIT`. So deploy can set more flex config such as `limits.cpu`.
Also bump memory request for oauth proxy to `32Mi` to keep 1:2 ratio (`64Mi` limit).
[APPSRE-8803](https://issues.redhat.com/browse/APPSRE-8803)

Extract resources to parameter

---

integration.sh
pr_check.sh

enable podman.sock as DOCKER_HOST, use mirrored gnomock-cleaner image.

fix ci in rhel8

---

Makefile
helm/.helmignore
helm/Chart.yaml
helm/templates/deployment.yaml
helm/templates/route.yaml
helm/templates/secrets.yaml
helm/templates/service-account.yaml
helm/templates/service.yaml
helm/values.yaml

The main reason for this change is to add logic to set the cert-manager annotations. 
Gabi instances using the default IngressController domain do not need to request specific certificates. Requesting them can cause a rate limit issue since all the subdomains are part of the same "exact set of hostnames". 
https://letsencrypt.org/docs/rate-limits/#new-certificates-per-exact-set-of-hostnames

Add a helm chart to deploy GABI

---

openshift/gabi.template.yaml

The secret created by the annotation in the `Service` collides with the secret created by Cert-manager in the `Route`.
Changing the name will store the certificates in different secrets.

Change gabi svc tls name

---

integration.sh
pr_check.sh
test/helper_test.go

Update gnomock integration tests to use Red Hat PostgreSQL 16 image
(registry.redhat.io/rhel9/postgresql-16) instead of the standard
docker.io/library/postgres image (via the quay.io/app-sre/postgres)
mirror and fix splunk integration tests.
Changes:
- Let the pull auth in PR checks be done via jenkins nodes pull
credentials to avoid handling multiple logins to different repos
- Use POSTGRESQL_* environment variables for Red Hat image compatibility
- Add custom healthcheck for PostgreSQL using correct credentials
- Add SPLUNK_GENERAL_TERMS environment variable to fix Splunk container startup
APPSRE-12463
Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>
Assisted-by: Claude noreply@anthropic.com

Fix integration tests
