- Dockerfile
- Makefile
- app_sre_build_deploy.sh
- app_sre_pr_check.sh
This PR adds necessary files for building docker image and CI jobs.
> Add build and pr-check job

- Dockerfile
- Makefile
> use multi-stage builds

- app_sre_build_deploy.sh
- app_sre_pr_check.sh
> login quay.io before build

- pkg/handlers/query.go
> remove ectra log

- openshift/gabi.template.yaml
> add host to route

- openshift/gabi-no-clusterrole.template.yaml
Relates to:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/32868
https://issues.redhat.com/browse/APPSRE-4356
> add gabi-no-clusterrole template file

- openshift/gabi-no-cluster-resources.template.yaml
Related to: https://issues.redhat.com/browse/APPSRE-4356
> edit/rename the no-cluster-resources deploy YAML: remove CRB

- README.md
part of https://issues.redhat.com/browse/APPSRE-4412
> update gabi start doc

- openshift/gabi-no-cluster-resources.template.yaml
- openshift/gabi.template.yaml
- Ignore minimum 3 replicas check
- Add readiness and liveliness probes to containers
- define resource requests and limits on openshift-oauth container
- remove trailing white spaces
Jira: https://issues.redhat.com/browse/APPSRE-4489
> Improve deployments to pass the DVO checks

- openshift/post-deploy-tests.template.yaml
> APPSRE-6090: Add an initial Job template to run post-deployment tests

- openshift/post-deploy-tests.template.yaml
> APPSRE-6090: Update the Job template to test staged deployment pipeline

- pkg/audit/audit.go
- pkg/handlers/healthcheck.go
> Format code with go fmt for consistency

- openshift/gabi.template.yaml
- openshift/post-deploy-tests.template.yaml
> APPSRE-6090: Expose listener internally using headless service

- openshift/post-deploy-tests.template.yaml
> APPSRE-6090: Update post-deployment job to call the /healthcheck endpoint

- build_deploy.sh
> Fix deployment script to address read-only variable reuse

- pkg/env/user/user.go
- test/integration_test.go
> Correctly handle legacy expiration when old users file is used

- README.md
- docs/healthcheck.md
> Update documentation to include changes to the project

- cmd/gabi/main.go
- internal/test/helper_test.go
- pkg/audit/splunk.go
- pkg/audit/splunk_test.go
- pkg/cmd/cmd.go
- pkg/env/db/db.go
- pkg/env/db/db_test.go
- pkg/env/db/driver.go
- pkg/env/splunk/splunk_test.go
- pkg/env/user/user.go
- pkg/env/user/user_test.go
- pkg/handlers/healthcheck.go
- pkg/handlers/healthcheck_test.go
- pkg/handlers/query.go
- pkg/handlers/query_test.go
- pkg/middleware/audit.go
- pkg/middleware/audit_test.go
- pkg/middleware/authorization_test.go
- pkg/middleware/expiration_test.go
- pkg/middleware/recovery.go
- pkg/middleware/recovery_test.go
- test/helper_test.go
- test/integration_test.go
> Address a number static linter warnings

- pkg/handlers/query.go
> Check type conversion when coercing row values into SQL raw bytes

- openshift/gabi.template.yaml
- openshift/post-deploy-tests.template.yaml
Part of [APPSRE-8174](https://issues.redhat.com/browse/APPSRE-8174), unset cpu limits to avoid cpu throttle.
> Unset CPU limits

- helm/templates/secrets.yaml
- helm/values.yaml
Change splunk Values to enable pass them as secretParameters from AppInterface
> Change splunk variables to allow secretParameters from AppInterface

- pkg/cmd/cmd.go
- pkg/env/db/db.go
- pkg/env/db/db_test.go
- pkg/gabi.go
- pkg/handlers/getdbname.go
- pkg/handlers/getdbname_test.go
- pkg/handlers/switchdbname.go
- pkg/handlers/switchdbname_test.go
Besides changing DBName in DBEnv, we must also change the db connection.
> fix switchdbname
